### ISSUE TITLE
使用Python3.9.10运行报错

### ISSUE THREAD

**Issue by DonotFreeze** [Everyb0dyLies/liarcom#2]
root@Friendlywrt:~# python /bin/liarcom.py 
欢迎使用专为北信科开发的liarcom
本项目由@EverybOdyLies开发维护
目前为测试版，如有任何问题欢迎在本项目的github页面提交issue
Traceback (most recent call last)：
  File "/bin/liarcom.py", line 511, in <module>
     liarcom = Liarcom() 
  File "/bin/liarcom.py", line 35, in __init__
     self._drcom = Drcom(self._usr, self._pwd)
  File "/bin/liarcom.py", line 171, in __init__
     self.mac = bytes().fromhex(LOCAL_MAC)
TypeError:fromhex() argument must be str, not int

使用r2s的friendlywrt 21.02.1版本固件，在其自带软件包管理界面安装了Python3.9.10（没装上其他版本的。。。）
（在Win10用Python3.9.10运行也是这个报错）

**Comment by LoneSpectator** [comment]
没法用3.7吗，3.9的我回头测试一下

**Comment by DonotFreeze** [comment]
很高兴你还能回复我的问题，但是我已经成功安装上py2.7且成功运行drcom项目的脚本，不过对于py3.7我印象中在openwrt的软件源里是没有提供的（至于三方软件源有没有我也不知道），如果可以的话还是希望你能维护你的项目以帮助更多的人

**Comment by LoneSpectator** [comment]
我会尽量持续更新，但是及时性大概是做不到了。2.7就是中文有点问题，用起来也是没啥问题的
